[project]
name = "tidy-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.37.31",
    "click>=8.1.8",
]

[dependency-groups]
dev = [
    "isort>=6.0.1",
]
